### ISSUE TITLE
CommanderType.Player does not show all players in the server in the auto-complete

### ISSUE THREAD

**Issue by phantomfills** [paradoxuum/commander#26]
CommanderType.Player currently only shows local player's user, @me, and @random in auto-completion box (regardless of whether someone's name has been partially entered)

**Comment by paradoxuum** [comment]
Can't reproduce this, are you using `@rbxts/commander@latest` (`0.3.2`) or `@rbxts/commander@next` (`0.3.3-dev.d18a576`)?
