### ISSUE TITLE
Set up monorepo, rename project

### ISSUE THREAD

**Issue by paradoxuum** [paradoxuum/commander#30]
As it stands, the project is made up of two parts:
- The framework itself, containing the registry, dispatcher, etc.
- The user interface, implemented in React

Ideally, these should be split into separate packages. If someone wants to make a custom interface, they shouldn't have to install the default user interface as well. This also leaves room for other packages, such as a package containing default commands.

There is also some consideration into a rebranding/renaming of the project. The main reason for this is that the name of this project is similar to another command console package, [Cmdr](https://eryn.io/Cmdr/). Currently, the plan is to change the name of the project to **centurion** after the project is set up as a monorepo. At that point, the following packages will be published, whenever it's ready to be released:
- `@rbxts/centurion`: The command framework
- `@rbxts/centurion-ui`: The default user interface
- In the future, possibly `@rbxts/centurion-commands`, containing a collection of commonly used commands.

**Comment by longuint** [comment]
I love how default commander palettes look, I would love to have a ui library based around those components used. I don't think it would require much work to have switches, buttons, etc. as built in components for use in projects and commander / centurion.
