### ISSUE TITLE
bind command

### ISSUE THREAD

**Issue by longuint** [paradoxuum/commander#31]
I don't know if this is implementable in the current version of commander but I would love to have to option to bind UserInputService / Mouse events to commands. For example tf2 and a lot of source games have the syntax:
`bind KEY "command"` 
I think this would add a lot of customizability, and allow users to tailor build commander around their experience.

**Comment by longuint** [comment]
After further deliberation, instead of a built-in command. There should be a decorator with a key combination.
This decorator's key combination should be similar to react-pretty-hooks's `useKeyPress()` function.

```ts
@Commander()
export ExampleBindableCommand {
    @Command()
    @Shortcut("LeftAlt+E")
    run(ctx: CommandContext) {}
}

```

The type for the shortcut could probably just be imported from react-pretty-hooks, KeyCodes.

A better way could probably be deliberated because I know the [luau package](https://github.com/paradoxuum/commander/issues/27) is planned. in

**Comment by sasial-dev** [comment]
Instead of a string, the shortcut could be `Array<Enum.KeyCode | Enum.KeyCode[]>`
This would allow for `@Shortcut([Enum.KeyCode.F4])` and mutiple keys such as `@Shortcut([[Enum.KeyCode.LeftAlt, Enum.KeyCode.E]])`.
And combined: `@Shortcut([Enum.KeyCode.F4, [Enum.KeyCode.LeftAlt, Enum.KeyCode.E]])`

**Comment by longuint** [comment]
You make an excellent point there, it would be easier to test and stub if the type builds of an array.

**Comment by paradoxuum** [comment]
I think it might be better to have this as an option passed to `@Command` rather than a separate decorator, since commands are synced to the client as `Map<string, CommandOptions>`

**Comment by longuint** [comment]
I am writing a pull request at the moment, it's using the shortcut as an option on the `CommandOptions` interface.
